### PR TITLE
fix: Block Explorer Page Update

### LINKED ISSUE #625: [explorer] Block page update
- [ ] put transactions table below details
- [ ] add empty state when there are no transactions
- [ ] put navigation to the previous and next block near the Height
- [ ] add a copy button to the hash
- [ ] add a table with all transactions 
- [ ] don't show incoming or outgoing tabs when there aren't any

[Link](https://www.figma.com/design/bfoVui5t00ph56kr6qIJNq/UI-Bugs?node-id=53-4726) to Figma
Use resizing logic from this issue – [link](https://github.com/NilFoundation/nil/issues/624)

Image

### PR DESCRIPTION
**Pull request by Abeeujah**
## Short Summary

Tis PR updates the block explorer page to the latest UI version designed.

## What Changes Were Made

- Fixed the display state for empty transactions
- Fixed the display state for block info
- Updated the transactions view state to include `<All | Incoming | Outgoing>`
- Added Pagination
- Updated the table to the new table layout
- Updated the new resizing logic.

## Related Issue

Fixes #625

## Screenshots / Visual Changes

localhost_5173_block_1_12375
localhost_5173_block_1_12376
localhost_5173_block_1_12376 (1)
localhost_5173_block_1_12384

## Checklist

- [x] I have read and followed the [Contributing Guide](https://github.com/NilFoundation/nil/blob/main/CONTRIBUTION-GUIDE.md)
- [x] I have tested the changes locally
- [x] I have added relevant tests (if applicable)
- [x] I have updated documentation/comments (if applicable)

### CODE REVIEW

**Comment by ukorvl** [comment]
Hey! As for pagination - let's use Pagination component from [ui-kit ](https://github.com/NilFoundation/ui-kit)for the sake of code minimization.
https://nilfoundation.github.io/ui-kit/?path=/docs/navigation-pagination--docs

**Comment by ukorvl** [comment]
"don't show incoming or outgoing tabs when there aren't any" - i think we still show it, am i correct?

**Comment by ukorvl** [comment]
Minor adjustment is needed here - please align this elements vertically to the center

**Comment by ukorvl** [comment]
When block is pending don't show an additional "Block" text
image

File: explorer_frontend/src/features/shared/components/InternalPageContainer.tsx [hunk 1]
```diff
@@ -14,8 +14,8 @@ export const InternalPageContainer: FC<InternalPageContainerProps> = ({ children
     <div
       className={css({
         gridColumn: "1 / 4",
-        paddingLeft: isMobile ? "0" : "32px",
-        paddingRight: isMobile ? "0" : "32px",
+        paddingInlineStart: isMobile ? "0" : "2rem",
```
Comment (ukorvl) [inline explorer_frontend/src/features/shared/components/InternalPageContainer.tsx:17]: I am not strongly opposite to it, but why changing to `rem`? As far as i remember the font size is not changing here.

Comment (Abeeujah) [reply explorer_frontend/src/features/shared/components/InternalPageContainer.tsx:17]: I'd revert that, I did use relative values here for cases where the users might choose to zoom | increase their font size, this helps the padding stay consistent with the font size | viewport.

**Review by idea404 — APPROVED** [review]
