### PR TITLE
[GH-561] Connection manager

### LINKED ISSUE #561: Implement connection manager with scoring mechanism
The goal is to keep "bad" peers from poisoning our lives. Of course, we [check][1] the signature of a block that comes to us and discard it if it is incorrect, but we are not protecting ourselves from spam. It is suggested to refer to [peerset][2] from `gossamer` as a reference.

In `gossamer` the corresponding mechanism is a rather complex entity, involving a full implementation from scratch of the `connmgr.ConnManager` interface, various connection pools, message queues, etc. etc. etc. 

Nevertheless, they started with quite [primitive mechanisms][3], which can serve as a good argument for us also not to overcomplicate ahead of time. Essentially, we just need to inject ourselves into the `network.Notifiee.Connected` processing and, depending on the reputation of the peer, decide whether to drop the connection with it or not.

The current state of `gossamer` was significantly approached in the task https://github.com/ChainSafe/gossamer/issues/1399. According to it, a [document][4] was written describing how such a mechanism is implemented in `substrate`. The implementation was added as part of https://github.com/ChainSafe/gossamer/pull/1791.

Separately, I was interested in the issue of choosing the values of numerous constants in `substrate`/`gossamer`. Investigation showed that they [started][5] with [arbitrarily chosen values][6] and then iteratively [tweaked and added new ones][7]. So I think we should do the same and add/tune constants as the subsystem evolves.

[1]: https://github.com/NilFoundation/nil/blob/072cfe9136645b9014fd5a17db4bbf37ed690279/nil/internal/collate/validator.go#L340
[2]: https://github.com/ChainSafe/gossamer/tree/ff33dc50f902b71bb7940a66269ac2bf194a59c7/dot/peerset
[3]: https://github.com/ChainSafe/gossamer/pull/1034/files
[4]: https://hackmd.io/@FyilpQ7sQ265a9xyqSxyLg/B1EIbIIfY
[5]: https://github.com/paritytech/substrate/pull/2110/commits/43ca14e752eb1d7606b963fbb8a907a4bf09dad7#diff-796f8563b2fdf3d032751227d48d9ee8a6e1190078e018d8e3d79293b670c0f0R314
[6]: https://github.com/paritytech/substrate/pull/2110/commits/904a521297f42cb9653e514588596deccf4164e3#r269980744
[7]: https://github.com/paritytech/substrate/pull/2229/files#diff-82213a47899307431bdf8ab0d4dddae30eadb5e8d1048083a26e9d18ccb90098

### PR DESCRIPTION
**Pull request by Un1oR**
Resolves #561

### CODE REVIEW

**Comment by Un1oR** [comment]
@dmtrskv @olegrok I will finalize the TODO edits in the code and the issue and PR descriptions a bit later, but I think it's already possible to evaluate the general points so that we don't waste time.

File: nil/internal/network/host.go [hunk 1]
```diff
@@ -15,46 +17,52 @@ import (
...
 // newHost creates a new libp2p host. It must be closed after use.
-func newHost(ctx context.Context, conf *Config) (Host, error) {
+func newHost(ctx context.Context, conf *Config) (Host, zerolog.Logger, error) {
 	addr := conf.IPV4Address
 	if addr == "" {
 		addr = "0.0.0.0"
 	}
 
-	options, err := getCommonOptions(ctx, conf.PrivateKey)
+	options, logger, err := getCommonOptions(ctx, conf)
```
Comment (olegrok) [inline nil/internal/network/host.go:63]: Maybe we need to call `getCommonOptions` outside `newHost`. I don't like that newHost returns logger now.

File: nil/internal/network/host.go [hunk 2]
```diff
@@ -102,14 +114,18 @@ func newClient(ctx context.Context, conf *Config) (Host, error) {
...
-			return nil, err
+			return nil, zerolog.Nop(), err
 		}
 	}
 
-	options, err := getCommonOptions(ctx, privateKey)
+	options, logger, err := getCommonOptions(ctx, &Config{PrivateKey: privateKey})
 	if err != nil {
-		return nil, err
+		return nil, zerolog.Logger{}, err
```
Comment (olegrok) [inline nil/internal/network/host.go:123]: It's a bit inconsistent with return above: `zerolog.Logger{}` vs `zerolog.Nop()`

File: nil/internal/network/connection_manager/notifiee.go [hunk 3]
```diff
@@ -0,0 +1,180 @@
...
+			n.logger.Error().Err(err).Msgf("Failed to close peer %s", peer)
+		}
+	}
+	var pi *peerInfo
+	var ok bool
+	if pi, ok = n.peerReputations[peer]; !ok {
+		pi = newPeerInfo(peer, 0, closeFunc)
+		n.peerReputations[peer] = pi
+	} else if pi.closeFunc == nil {
+		pi.closeFunc = closeFunc
```
Comment (olegrok) [inline nil/internal/network/connection_manager/notifiee.go:78]: I guess you can create `closeFunc` under this if

File: nil/internal/network/connection_manager/peer_info.go [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+// and will be able to use it if necessary.
+type peerInfo struct {
+	id         peer.ID
+	reputation Reputation
+	closeFunc  func()
+}
+
+func (pi *peerInfo) closePeer(logger zerolog.Logger) {
+	if pi.closeFunc != nil {
+		logger.Debug().Stringer("peerId", pi.id).Msg("Disconnecting banned peer")
```
Comment (olegrok) [inline nil/internal/network/connection_manager/peer_info.go:27]: You can log this right inside `pi.closeFunc` and don't pass logger inside `closePeer`

File: nil/internal/network/connection_manager/testaide.ge.go [hunk 5]
```diff
@@ -0,0 +1,31 @@
+//go:build test
```
[the remark this answers is not in the document]
Comment (Un1oR) [reply nil/internal/network/connection_manager/testaide.ge.go:1]: A typo)

File: nil/internal/network/host.go (hunk 1 above)
Comment (Un1oR) [reply nil/internal/network/host.go:63]: I don't have a good opinion on that. I can do that if you think it's best.

Comment (Un1oR) [reply nil/internal/network/host.go:63]: Frankly, this would affect `newClient`/`NewClientManager`, and thus the private key work that happens there. I'm not sure how good and timely this is. If not critical, we can make some changes here as a separate PR.

File: nil/internal/network/connection_manager/config.go [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+	// ReputationChangeSettings is a map of reasons for reputation changes and the
+	// reputation change that should be applied.
+	ReputationChangeSettings ReputationChangeSettings `yaml:"reputationChangeSettings,omitempty"`
+
+	clock clockwork.Clock `yaml:"-"`
+}
+
+func NewDefaultConfig() *Config {
+	return &Config{
+		DecayReputationPerSecondPercent: 2, // A bit low, then 35 seconds to reduce reputation by half
```
Comment (olegrok) [inline nil/internal/network/connection_manager/config.go:42]: I'd add a formula to calculate it. Connection between 32 and 2 is not so obvious.

File: nil/internal/network/connection_manager/connection_manager.go [hunk 7]
```diff
@@ -0,0 +1,41 @@
...
+	return cm.notifee
+}
+
+var _ libp2pconnmgr.ConnManager = (*withCustomNotifeeDecorator)(nil)
+
+func NewConnectionManagerWithPeerReputationTracking(
+	ctx context.Context,
+	conf *Config,
+	logger zerolog.Logger,
+	low, hi int,
```
Comment (olegrok) [inline nil/internal/network/connection_manager/connection_manager.go:28]: I suggest to change the order of arguments here. Usually we pass logger as the last argument.
Here it's impossible to make it the latest but let's move it a bit closer to the end.

File: nil/internal/network/host.go [hunk 8]
```diff
@@ -15,46 +17,52 @@ import (
...
+		return nil, zerolog.Nop(), err
 	}
 
-	pid, err := peer.IDFromPublicKey(privateKey.GetPublic())
+	logger := internal.Logger.With().
+		Stringer(logging.FieldP2PIdentity, pid).
+		Logger()
+
+	cm, err := connection_manager.NewConnectionManagerWithPeerReputationTracking(
+		ctx, conf.ConnectionManagerConfig, logger, 100, 400, defaultGracePeriod)
```
Comment (olegrok) [inline nil/internal/network/host.go:38]: What do low and hight mean here?
Why did you choose 100 and 400 here?

Comment (Un1oR) [reply nil/internal/network/host.go:38]: This is the transposed code, I didn't change the values

File: nil/internal/network/connection_manager/connection_manager.go (hunk 7 above)
Comment (Un1oR) [reply nil/internal/network/connection_manager/connection_manager.go:28]: I don't really want to break up the argument list that is passed to `connmgr.NewConnManager` as is.

File: nil/internal/network/host.go (hunk 8 above)
Comment (olegrok) [reply nil/internal/network/host.go:38]: It's worth to understand that they mean

Comment (Un1oR) [reply nil/internal/network/host.go:38]: > // lo and hi are watermarks governing the number of connections that'll be maintained.
// When the peer count exceeds the 'high watermark', as many peers will be pruned (and
// their connections terminated) until 'low watermark' peers remain.

**Review by olegrok — APPROVED** [review]
