### PR TITLE
[docs] miscellaneous fixes

### LINKED ISSUE #291: Add an FT example to docs
# Problem statement

The current NFT example in the docs (https://docs.nil.foundation/nil/smart-contracts/tokens) is a bit complex and difficult to understand. 

# Solution

Add a new example for a simple fungible token. 
Also add a more detailed elaboration on how to use `NilTokenBase.sol`.

### LINKED ISSUE #351: Fix devnet config-gen docs
This guide: https://docs.nil.foundation/nil/nild/#complete-devnet-with-2-validators-an-archive-node-and-an-rpc-node

It says I should do: `nild run --config myDevnet/conf/nil-0`, but in fact I need to do `nild run --config myDevnet/conf/nil-0/nild.yaml`

Also the current example works for everything except the archive node, which, when started prints:

```
invalid configuration error="On archive node, number of bootstrap peers must be equal to the number of shards"
```

### PR DESCRIPTION
**Pull request by khannanov-nil**
This diff closes several minor GitHub issues and addresses comments received in other channels.

* Closes #351 by amending links to config files when running `nild`
* Closes #291 by adding a simple FT example to docs
* Improves the description of `npm run build` in the Hardhat tutorial
* Adjusts Nil.js snippets in several tutorial
* Fixes =nil; CLI sidebar by removing the duplicate section and restoring 'Error handling'

### CODE REVIEW

File: docs/sidebar-nil.js [hunk 1]
```diff
@@ -193,6 +188,11 @@ export default {
               id: "nilcli/calling-smart-contract",
             },
           ],
+        },
+                {
```
Comment (olegrok) [inline docs/sidebar-nil.js:192]:
```suggestion
        {
```

File: docs/nil/nild.mdx [hunk 2]
```diff
@@ -84,10 +83,10 @@ $ nild gen-configs myDevnet.yaml --basedir myDevnet/var
 The configuration files will be created in `myDevnet/conf`. Start the services by running:
 
 ```bash
-$ nild run --config myDevnet/conf/nil-0  # start first validator
-$ nild run --config myDevnet/conf/nil-1  # start second validator
-$ nild archive --config myDevnet/conf/nil-archive-0  # start archive node
-$ nild rpc --config myDevnet/conf/nil-rpc-0  # start RPC node
+$ nild run --config myDevnet/conf/nil-0/nild.yaml  # start first validator
+$ nnild run --config myDevnet/conf/nil-1/nild.yaml  # start second validator
```
Comment (olegrok) [inline docs/nil/nild.mdx:87]:
```suggestion
$ nild run --config myDevnet/conf/nil-1/nild.yaml  # start second validator
```

File: docs/nil/nild.mdx [hunk 3]
```diff
@@ -68,10 +70,7 @@ nil_rpc_config:
     archiveNodeIndices: [ 0 ]
 ```
 
-If needed, tweak the amount of shards and validators, the distribution
-of shards between validators and other parameters. The `bootstrapPeersIdx` and
-`dhtBootstrapPeersIdx` settings are lists of validators IDs in this
-spec.
+If needed, tweak the amount of shards and validators, the distribution of shards between validators and other parameters. The `bootstrapPeersIdx` and `dhtBootstrapPeersIdx` settings are lists of validators IDs in this spec.
```
Comment (avm) [inline docs/nil/nild.mdx:73]: I would prefer that we not remove line breaks.
